name: Deploy to cPanel (PM2)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Upload build to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "client/dist,admin/dist"
          target: "/home/availjom/web-avail-jombang"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            echo "🚀 Starting deployment..."

            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 22

            cd /home/availjom/web-avail-jombang

            echo "📥 Pull latest code"
            git pull origin main

            echo "📦 Install production deps"
            npm install --omit=dev

            echo "🔄 Restart app"
            pm2 reload web-avail-jombang || pm2 start ecosystem.config.js

            echo "✅ Deployment finished"